openapi: 3.0.3
info:
  title: Lumen
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/articles:
    get:
      summary: 'Return all articles'
      operationId: returnAllArticles
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: null
                  data:
                    current_page: 1
                    data:
                      -
                        id: 20
                        title: 'Ea dolor.'
                        cover: 'https://via.placeholder.com/150x150.png/009988?text=a'
                        short_description: "Duchess, 'and that's why. Pig!' She said the Footman, and began to tremble. Alice looked down at the..."
                        tags:
                          id: 5
                          name: Quam.
                      -
                        id: 19
                        title: Et.
                        cover: 'https://via.placeholder.com/150x150.png/00ddaa?text=cumque'
                        short_description: "Don't let me hear the rattle of the party were placed along the sea-shore--' 'Two lines!' cried the..."
                        tags:
                          id: 8
                          name: Maxime.
                      -
                        id: 18
                        title: Soluta.
                        cover: 'https://via.placeholder.com/150x150.png/004455?text=delectus'
                        short_description: "OURS they had a head unless there was no one listening, this time, as it was good practice to say 'D..."
                        tags:
                          id: 7
                          name: Dolor.
                      -
                        id: 17
                        title: Vel.
                        cover: 'https://via.placeholder.com/150x150.png/001100?text=cumque'
                        short_description: "I'm a deal faster than it does.' 'Which would NOT be an old conger-eel, that used to it in time,' sa..."
                        tags:
                          id: 9
                          name: Omnis.
                      -
                        id: 16
                        title: 'Aut quia.'
                        cover: 'https://via.placeholder.com/150x150.png/0022aa?text=voluptatem'
                        short_description: 'Alice, very loudly and decidedly, and there was no label this time she had forgotten the little gold...'
                        tags:
                          id: 1
                          name: Dolor.
                      -
                        id: 15
                        title: 'Eaque ea.'
                        cover: 'https://via.placeholder.com/150x150.png/005500?text=voluptas'
                        short_description: "Mock Turtle went on, '\"--found it advisable to go among mad people,' Alice remarked. 'Right, as usua..."
                        tags:
                          id: 8
                          name: Maxime.
                      -
                        id: 14
                        title: 'Ea iure.'
                        cover: 'https://via.placeholder.com/150x150.png/0055dd?text=sint'
                        short_description: "March Hare. 'I didn't know that Cheshire cats always grinned; in fact, I didn't know that cats COULD..."
                        tags:
                          id: 5
                          name: Quam.
                      -
                        id: 13
                        title: Quia.
                        cover: 'https://via.placeholder.com/150x150.png/003399?text=at'
                        short_description: "Queen, and in another minute there was no 'One, two, three, and away,' but they were all turning int..."
                        tags:
                          id: 5
                          name: Quam.
                      -
                        id: 12
                        title: 'Quos et.'
                        cover: 'https://via.placeholder.com/150x150.png/00ff33?text=mollitia'
                        short_description: "March Hare: she thought there was a dead silence instantly, and Alice called after her. 'I've someth..."
                        tags:
                          id: 10
                          name: Eos.
                      -
                        id: 11
                        title: 'Ut ad.'
                        cover: 'https://via.placeholder.com/150x150.png/009966?text=nulla'
                        short_description: "No room!' they cried out when they liked, so that by the English, who wanted leaders, and had come b..."
                        tags:
                          id: 1
                          name: Dolor.
                    first_page_url: 'http://localhost/api/articles?page=1'
                    from: 1
                    last_page: 2
                    last_page_url: 'http://localhost/api/articles?page=2'
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/articles?page=1'
                        label: '1'
                        active: true
                      -
                        url: 'http://localhost/api/articles?page=2'
                        label: '2'
                        active: false
                      -
                        url: 'http://localhost/api/articles?page=2'
                        label: 'Next &raquo;'
                        active: false
                    next_page_url: 'http://localhost/api/articles?page=2'
                    path: 'http://localhost/api/articles'
                    per_page: 10
                    prev_page_url: null
                    to: 10
                    total: 20
                  message: 'All Articles'
                  status: success
                properties:
                  errors:
                    type: string
                    example: null
                  data:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      data:
                        type: array
                        example:
                          -
                            id: 20
                            title: 'Ea dolor.'
                            cover: 'https://via.placeholder.com/150x150.png/009988?text=a'
                            short_description: "Duchess, 'and that's why. Pig!' She said the Footman, and began to tremble. Alice looked down at the..."
                            tags:
                              id: 5
                              name: Quam.
                          -
                            id: 19
                            title: Et.
                            cover: 'https://via.placeholder.com/150x150.png/00ddaa?text=cumque'
                            short_description: "Don't let me hear the rattle of the party were placed along the sea-shore--' 'Two lines!' cried the..."
                            tags:
                              id: 8
                              name: Maxime.
                          -
                            id: 18
                            title: Soluta.
                            cover: 'https://via.placeholder.com/150x150.png/004455?text=delectus'
                            short_description: "OURS they had a head unless there was no one listening, this time, as it was good practice to say 'D..."
                            tags:
                              id: 7
                              name: Dolor.
                          -
                            id: 17
                            title: Vel.
                            cover: 'https://via.placeholder.com/150x150.png/001100?text=cumque'
                            short_description: "I'm a deal faster than it does.' 'Which would NOT be an old conger-eel, that used to it in time,' sa..."
                            tags:
                              id: 9
                              name: Omnis.
                          -
                            id: 16
                            title: 'Aut quia.'
                            cover: 'https://via.placeholder.com/150x150.png/0022aa?text=voluptatem'
                            short_description: 'Alice, very loudly and decidedly, and there was no label this time she had forgotten the little gold...'
                            tags:
                              id: 1
                              name: Dolor.
                          -
                            id: 15
                            title: 'Eaque ea.'
                            cover: 'https://via.placeholder.com/150x150.png/005500?text=voluptas'
                            short_description: "Mock Turtle went on, '\"--found it advisable to go among mad people,' Alice remarked. 'Right, as usua..."
                            tags:
                              id: 8
                              name: Maxime.
                          -
                            id: 14
                            title: 'Ea iure.'
                            cover: 'https://via.placeholder.com/150x150.png/0055dd?text=sint'
                            short_description: "March Hare. 'I didn't know that Cheshire cats always grinned; in fact, I didn't know that cats COULD..."
                            tags:
                              id: 5
                              name: Quam.
                          -
                            id: 13
                            title: Quia.
                            cover: 'https://via.placeholder.com/150x150.png/003399?text=at'
                            short_description: "Queen, and in another minute there was no 'One, two, three, and away,' but they were all turning int..."
                            tags:
                              id: 5
                              name: Quam.
                          -
                            id: 12
                            title: 'Quos et.'
                            cover: 'https://via.placeholder.com/150x150.png/00ff33?text=mollitia'
                            short_description: "March Hare: she thought there was a dead silence instantly, and Alice called after her. 'I've someth..."
                            tags:
                              id: 10
                              name: Eos.
                          -
                            id: 11
                            title: 'Ut ad.'
                            cover: 'https://via.placeholder.com/150x150.png/009966?text=nulla'
                            short_description: "No room!' they cried out when they liked, so that by the English, who wanted leaders, and had come b..."
                            tags:
                              id: 1
                              name: Dolor.
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 20
                            title:
                              type: string
                              example: 'Ea dolor.'
                            cover:
                              type: string
                              example: 'https://via.placeholder.com/150x150.png/009988?text=a'
                            short_description:
                              type: string
                              example: "Duchess, 'and that's why. Pig!' She said the Footman, and began to tremble. Alice looked down at the..."
                            tags:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 5
                                name:
                                  type: string
                                  example: Quam.
                      first_page_url:
                        type: string
                        example: 'http://localhost/api/articles?page=1'
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 2
                      last_page_url:
                        type: string
                        example: 'http://localhost/api/articles?page=2'
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/articles?page=1'
                            label: '1'
                            active: true
                          -
                            url: 'http://localhost/api/articles?page=2'
                            label: '2'
                            active: false
                          -
                            url: 'http://localhost/api/articles?page=2'
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      next_page_url:
                        type: string
                        example: 'http://localhost/api/articles?page=2'
                      path:
                        type: string
                        example: 'http://localhost/api/articles'
                      per_page:
                        type: integer
                        example: 10
                      prev_page_url:
                        type: string
                        example: null
                      to:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 20
                  message:
                    type: string
                    example: 'All Articles'
                  status:
                    type: string
                    example: success
      tags:
        - Endpoints
      security: []
  '/api/articles/{id}':
    get:
      summary: ''
      operationId: getApiArticlesId
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: 'No query results for model [App\Models\Articles] earum'
                  data: null
                  message: 'An error occurred error'
                  status: error
                properties:
                  errors:
                    type: string
                    example: 'No query results for model [App\Models\Articles] earum'
                  data:
                    type: string
                    example: null
                  message:
                    type: string
                    example: 'An error occurred error'
                  status:
                    type: string
                    example: error
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: ''
        example: earum
        required: true
        schema:
          type: string
  '/api/articles/{id}/like':
    post:
      summary: ''
      operationId: postApiArticlesIdLike
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: ''
        example: et
        required: true
        schema:
          type: string
  '/api/articles/{id}/view':
    post:
      summary: ''
      operationId: postApiArticlesIdView
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: ''
        example: beatae
        required: true
        schema:
          type: string
  '/api/articles/{id}/comment':
    post:
      summary: ''
      operationId: postApiArticlesIdComment
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: ''
        example: et
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
